name: Deploy WebGL to GitHub Pages (user site)

on:
  push:
    branches: [ main ]   # build on pushes to main

permissions:
  contents: write   # <- required to push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Assemble site
        run: |
          mkdir -p public
          cp -r webgl/Build public/Build
          if [ -d webgl/TemplateData ]; then cp -r webgl/TemplateData public/TemplateData; fi
          cp webgl/index.html public/index.html
          touch public/.nojekyll

      - name: Deploy to main (root)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: main           # user sites must serve from main
          keep_files: true               # don't delete existing repo files
          force_orphan: false            # keep history; don't wipe main
